const PASSWORD = 'ICHICH';
const state = { reservations: [], expenses: [], currentMonth: new Date(), apiUrl: localStorage.getItem('ichkiichpanApiUrl') || '' };
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const money = (n) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n||0));
const dateFmt = (d, opts={month:'short',day:'numeric'}) => new Intl.DateTimeFormat('en-US',opts).format(new Date(`${d}T12:00:00`));
const today = () => new Date(new Date().toDateString());
const daysBetween = (a,b) => Math.round((new Date(`${b}T12:00:00`)-new Date(`${a}T12:00:00`))/86400000);
const uid = (prefix) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`.toUpperCase();

const demoReservations = [
 {id:'RES-001',confirmationNumber:'AIR-84K2',guestName:'Sofia Martinez',platform:'Airbnb',agencyName:'',checkIn:isoOffset(2),checkOut:isoOffset(5),guests:8,reservationAmount:28600,cleaningFee:1800,commission:4200,taxes:3100,amountReceived:22000,status:'Confirmed',cleaningStatus:'Scheduled',notes:'Prepare kayaks and extra towels.'},
 {id:'RES-002',confirmationNumber:'VRB-191A',guestName:'Daniel Brooks',platform:'Vrbo',agencyName:'',checkIn:isoOffset(9),checkOut:isoOffset(13),guests:10,reservationAmount:34400,cleaningFee:1800,commission:5200,taxes:3700,amountReceived:34400,status:'Confirmed',cleaningStatus:'Pending',notes:''},
 {id:'RES-003',confirmationNumber:'AG-211',guestName:'Camila Ortega',platform:'Agency',agencyName:'Maya Escapes',checkIn:isoOffset(18),checkOut:isoOffset(21),guests:6,reservationAmount:24500,cleaningFee:1800,commission:2450,taxes:2700,amountReceived:10000,status:'Pending',cleaningStatus:'Pending',notes:'Agency requested late arrival.'},
];
const demoExpenses = [
 {id:'EXP-001',date:isoOffset(-5),category:'Cleaning',vendor:'María',description:'Post-stay cleaning',reservationId:'RES-000',amount:1600,notes:''},
 {id:'EXP-002',date:isoOffset(-2),category:'Supplies',vendor:'Costco',description:'Towels and toiletries',reservationId:'',amount:2380,notes:''}
];
function isoOffset(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function hydrate(){ state.reservations = JSON.parse(localStorage.getItem('ichkiichpanReservations')||'null') || demoReservations; state.expenses = JSON.parse(localStorage.getItem('ichkiichpanExpenses')||'null') || demoExpenses; }
function persist(){localStorage.setItem('ichkiichpanReservations',JSON.stringify(state.reservations));localStorage.setItem('ichkiichpanExpenses',JSON.stringify(state.expenses));}
function enrich(r){const nights=daysBetween(r.checkIn,r.checkOut);const balance=Math.max(0,Number(r.reservationAmount||0)-Number(r.amountReceived||0));const net=Number(r.reservationAmount||0)-Number(r.commission||0)-Number(r.taxes||0);const now=today(),cin=new Date(`${r.checkIn}T12:00:00`),cout=new Date(`${r.checkOut}T12:00:00`);let stayStatus=r.status==='Cancelled'?'Cancelled':now<cin?'Upcoming':now<cout?'Checked In':'Completed';return {...r,nights,balance,net,daysUntil:daysBetween(new Date().toISOString().slice(0,10),r.checkIn),stayStatus};}
function platformClass(p){return p==='Airbnb'?'airbnb':p==='Vrbo'?'vrbo':p==='Booking.com'?'booking':'agency'}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(showToast.t);showToast.t=setTimeout(()=>t.hidden=true,2400)}

$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#passwordInput').value===PASSWORD){sessionStorage.setItem('ichAuth','1');openApp()}else $('#loginError').hidden=false});
$('#logoutButton').addEventListener('click',()=>{sessionStorage.removeItem('ichAuth');location.reload()});
function openApp(){ $('#loginView').hidden=true;$('#appView').hidden=false;hydrate();renderAll(); }
if(sessionStorage.getItem('ichAuth')==='1') openApp();

$$('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));
function switchView(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$('#viewTitle').textContent=name[0].toUpperCase()+name.slice(1);if(name==='calendar')renderCalendar();}

function renderAll(){renderDashboard();renderReservations();renderExpenses();renderReports();renderCalendar();$('#apiUrlInput').value=state.apiUrl;$('#syncStatus').textContent=state.apiUrl?'Connected':'Local mode';}
function renderDashboard(){const rs=state.reservations.map(enrich).filter(r=>r.status!=='Cancelled'), ex=state.expenses;const month=new Date().getMonth(),year=new Date().getFullYear();const rm=rs.filter(r=>{const d=new Date(`${r.checkIn}T12:00:00`);return d.getMonth()===month&&d.getFullYear()===year});const em=ex.filter(x=>{const d=new Date(`${x.date}T12:00:00`);return d.getMonth()===month&&d.getFullYear()===year});const gross=rm.reduce((s,r)=>s+Number(r.reservationAmount||0),0),expenses=em.reduce((s,x)=>s+Number(x.amount||0),0),occupied=rm.reduce((s,r)=>s+r.nights,0),days=new Date(year,month+1,0).getDate();const next=rs.filter(r=>r.daysUntil>=0).sort((a,b)=>a.daysUntil-b.daysUntil)[0];const metrics=[['Current guest',rs.find(r=>r.stayStatus==='Checked In')?.guestName||'None','Live stay'],['Next check-in',next?.checkIn?dateFmt(next.checkIn):'—','At 3:00 PM'],['Occupancy',`${Math.min(100,Math.round(occupied/days*100))}%`,`${occupied} booked nights`],['Gross revenue',money(gross),'This month'],['Estimated net',money(gross-expenses),'Before owner costs'],['Pending balances',money(rs.reduce((s,r)=>s+r.balance,0)),'All active reservations'],['Cleaning due',rs.filter(r=>r.daysUntil>=0&&r.daysUntil<=2&&r.cleaningStatus!=='Completed').length,'Within 2 days'],['Conflicts',findConflicts(rs).size,'Needs review']];$('#metricsGrid').innerHTML=metrics.map(m=>`<article class="metric-card"><div class="label">${m[0]}</div><div class="value">${m[1]}</div><div class="hint">${m[2]}</div></article>`).join('');renderMiniCalendar();renderPriority(rs);renderUpcoming(rs);renderPending(rs)}
function renderPriority(rs){const items=[];rs.forEach(r=>{if(r.balance>0&&r.daysUntil<=2&&r.daysUntil>=0)items.push({type:'danger',title:`Payment pending: ${r.guestName}`,sub:`${money(r.balance)} due before ${dateFmt(r.checkIn)}`});if(r.cleaningStatus!=='Completed'&&r.daysUntil<=1&&r.daysUntil>=0)items.push({type:'warn',title:'Cleaning not complete',sub:`${r.guestName} checks in ${r.daysUntil===0?'today':'tomorrow'}`})});findConflicts(rs).forEach(id=>{const r=rs.find(x=>x.id===id);items.push({type:'danger',title:'Reservation conflict',sub:`Review ${r?.guestName||id}`})});$('#priorityList').innerHTML=items.length?items.slice(0,6).map(i=>`<div class="priority-item ${i.type}"><div><strong>${i.title}</strong><div class="muted small">${i.sub}</div></div></div>`).join(''):'<p class="muted">Nothing urgent right now.</p>'}
function renderUpcoming(rs){const list=rs.filter(r=>r.daysUntil>=0).sort((a,b)=>a.daysUntil-b.daysUntil).slice(0,5);$('#upcomingList').innerHTML=list.map(r=>`<div class="reservation-card"><div><strong>${r.guestName}</strong><div class="muted small">${dateFmt(r.checkIn)}–${dateFmt(r.checkOut)} · ${r.guests} guests · ${r.platform}</div></div><button onclick="editReservation('${r.id}')">Edit</button></div>`).join('')||'<p class="muted">No upcoming reservations.</p>'}
function renderPending(rs){const list=rs.filter(r=>r.balance>0).sort((a,b)=>b.balance-a.balance).slice(0,5);$('#pendingList').innerHTML=list.map(r=>`<div class="pending-item"><div><strong>${r.guestName}</strong><div class="muted small">${dateFmt(r.checkIn)} · ${r.platform}</div></div><div><strong>${money(r.balance)}</strong><button onclick="editReservation('${r.id}')">Update</button></div></div>`).join('')||'<p class="muted">No pending balances.</p>'}
function renderMiniCalendar(){const d=new Date();$('#miniCalendar').innerHTML=calendarHTML(d.getFullYear(),d.getMonth(),false)}
function renderCalendar(){const d=state.currentMonth;$('#calendarTitle').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(d);$('#fullCalendar').innerHTML=calendarHTML(d.getFullYear(),d.getMonth(),true)}
function calendarHTML(year,month,full){const start=new Date(year,month,1-new Date(year,month,1).getDay()),cells=[];for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const iso=day.toISOString().slice(0,10),bookings=state.reservations.filter(r=>r.status!=='Cancelled'&&iso>=r.checkIn&&iso<r.checkOut);cells.push(`<div class="calendar-cell ${day.getMonth()!==month?'outside':''}"><div class="day-number">${day.getDate()}</div>${bookings.slice(0,full?3:2).map(r=>`<div class="booking-chip ${platformClass(r.platform)}" title="${r.guestName}" onclick="editReservation('${r.id}')">${r.guestName}</div>`).join('')}${bookings.length>(full?3:2)?`<div class="muted small">+${bookings.length-(full?3:2)} more</div>`:''}</div>`)}return ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="day-number">${x}</div>`).join('')+cells.join('')}
$('#prevMonth').onclick=()=>{state.currentMonth=new Date(state.currentMonth.getFullYear(),state.currentMonth.getMonth()-1,1);renderCalendar()};
$('#nextMonth').onclick=()=>{state.currentMonth=new Date(state.currentMonth.getFullYear(),state.currentMonth.getMonth()+1,1);renderCalendar()};

function renderReservations(){const q=($('#reservationSearch')?.value||'').toLowerCase(),filter=$('#reservationFilter')?.value||'all';const rows=state.reservations.map(enrich).filter(r=>{const text=`${r.guestName} ${r.confirmationNumber} ${r.platform}`.toLowerCase();if(q&&!text.includes(q))return false;if(filter==='upcoming'&&r.stayStatus!=='Upcoming')return false;if(filter==='checked-in'&&r.stayStatus!=='Checked In')return false;if(filter==='pending-payment'&&r.balance<=0)return false;if(filter==='cleaning'&&r.cleaningStatus==='Completed')return false;if(filter==='cancelled'&&r.status!=='Cancelled')return false;return true}).sort((a,b)=>a.checkIn.localeCompare(b.checkIn));$('#reservationsTableBody').innerHTML=rows.map(r=>`<tr><td><strong>${r.guestName}</strong><div class="muted small">${r.confirmationNumber||r.id}</div></td><td><span class="badge ${platformClass(r.platform)}">${r.platform}</span></td><td>${dateFmt(r.checkIn)}–${dateFmt(r.checkOut)}<div class="muted small">${r.nights} nights</div></td><td>${r.guests}</td><td>${money(r.reservationAmount)}</td><td>${money(r.balance)}</td><td><span class="badge ${r.cleaningStatus==='Pending'?'pending':''}">${r.cleaningStatus}</span></td><td><span class="badge ${r.status==='Cancelled'?'cancelled':''}">${r.stayStatus}</span></td><td><button class="action-button" onclick="editReservation('${r.id}')">Edit</button></td></tr>`).join('')}
$('#reservationSearch').addEventListener('input',renderReservations);$('#reservationFilter').addEventListener('change',renderReservations);
function renderExpenses(){const map=Object.fromEntries(state.reservations.map(r=>[r.id,r.guestName]));$('#expensesTableBody').innerHTML=state.expenses.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${dateFmt(x.date,{year:'numeric',month:'short',day:'numeric'})}</td><td>${x.category}</td><td>${x.vendor||'—'}</td><td>${x.description||'—'}</td><td>${map[x.reservationId]||'—'}</td><td>${money(x.amount)}</td><td><button class="action-button" onclick="deleteExpense('${x.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">No expenses.</td></tr>'}
function renderReports(){const rs=state.reservations.map(enrich).filter(r=>r.status!=='Cancelled'),gross=rs.reduce((s,r)=>s+Number(r.reservationAmount||0),0),net=rs.reduce((s,r)=>s+r.net,0),exp=state.expenses.reduce((s,x)=>s+Number(x.amount||0),0),nights=rs.reduce((s,r)=>s+r.nights,0);const metrics=[['Total revenue',money(gross)],['Net after fees/tax',money(net)],['Operating expenses',money(exp)],['Estimated profit',money(net-exp)],['Average nightly rate',money(nights?gross/nights:0)]];$('#reportsGrid').innerHTML=metrics.map(m=>`<article class="metric-card"><div class="label">${m[0]}</div><div class="value">${m[1]}</div></article>`).join('');renderBars('#platformReport',groupSum(rs,'platform','reservationAmount'));renderBars('#expenseReport',groupSum(state.expenses,'category','amount'))}
function groupSum(arr,key,val){return Object.entries(arr.reduce((o,x)=>(o[x[key]]=(o[x[key]]||0)+Number(x[val]||0),o),{})).sort((a,b)=>b[1]-a[1])}
function renderBars(sel,data){const max=Math.max(1,...data.map(x=>x[1]));$(sel).innerHTML=data.map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><strong>${money(v)}</strong></div>`).join('')||'<p class="muted">No data yet.</p>'}
function findConflicts(rs){const ids=new Set();for(let i=0;i<rs.length;i++)for(let j=i+1;j<rs.length;j++)if(rs[i].checkIn<rs[j].checkOut&&rs[i].checkOut>rs[j].checkIn){ids.add(rs[i].id);ids.add(rs[j].id)}return ids}

const rDialog=$('#reservationDialog'),rForm=$('#reservationForm');$('#newReservationBtn').onclick=()=>openReservation();$$('.close-modal').forEach(b=>b.onclick=()=>rDialog.close());
function openReservation(r=null){rForm.reset();$('#deleteReservationBtn').hidden=!r;$('#reservationModalTitle').textContent=r?'Edit reservation':'New reservation';const data=r||{id:'',platform:'Airbnb',guests:2,status:'Confirmed',cleaningStatus:'Pending',checkIn:isoOffset(1),checkOut:isoOffset(3)};Object.entries(data).forEach(([k,v])=>{if(rForm.elements[k])rForm.elements[k].value=v??''});rDialog.showModal()}
window.editReservation=id=>openReservation(state.reservations.find(r=>r.id===id));
rForm.addEventListener('submit',e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(rForm));['guests','reservationAmount','cleaningFee','commission','taxes','amountReceived'].forEach(k=>fd[k]=Number(fd[k]||0));fd.id=fd.id||uid('RES');const idx=state.reservations.findIndex(r=>r.id===fd.id);if(idx>=0)state.reservations[idx]=fd;else state.reservations.push(fd);persist();rDialog.close();renderAll();showToast('Reservation saved');syncMutation('saveReservation',fd)});
$('#deleteReservationBtn').onclick=()=>{const id=rForm.elements.id.value;if(!id)return;state.reservations=state.reservations.filter(r=>r.id!==id);persist();rDialog.close();renderAll();showToast('Reservation deleted');syncMutation('deleteReservation',{id})};

const eDialog=$('#expenseDialog'),eForm=$('#expenseForm');$('#newExpenseBtn').onclick=()=>{eForm.reset();eForm.elements.date.value=isoOffset(0);$('#expenseReservationSelect').innerHTML='<option value="">Not linked</option>'+state.reservations.map(r=>`<option value="${r.id}">${r.guestName} · ${dateFmt(r.checkIn)}</option>`).join('');eDialog.showModal()};$$('.close-expense').forEach(b=>b.onclick=()=>eDialog.close());eForm.addEventListener('submit',e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(eForm));fd.id=uid('EXP');fd.amount=Number(fd.amount||0);state.expenses.push(fd);persist();eDialog.close();renderAll();showToast('Expense saved');syncMutation('saveExpense',fd)});window.deleteExpense=id=>{state.expenses=state.expenses.filter(x=>x.id!==id);persist();renderAll();showToast('Expense deleted');syncMutation('deleteExpense',{id})};

$('#saveSettingsBtn').onclick=()=>{state.apiUrl=$('#apiUrlInput').value.trim();localStorage.setItem('ichkiichpanApiUrl',state.apiUrl);$('#syncStatus').textContent=state.apiUrl?'Connected':'Local mode';showToast('Connection saved')};$('#syncButton').onclick=syncData;
async function syncData(){if(!state.apiUrl){showToast('Add the Apps Script URL in Settings');switchView('settings');return}try{$('#syncStatus').textContent='Syncing…';const res=await fetch(`${state.apiUrl}?action=getAll`);const data=await res.json();if(data.reservations)state.reservations=data.reservations;if(data.expenses)state.expenses=data.expenses;persist();renderAll();$('#syncStatus').textContent='Connected';showToast('Data synced')}catch(err){console.error(err);$('#syncStatus').textContent='Sync error';showToast('Could not sync. Local changes are safe.')}}
async function syncMutation(action,payload){if(!state.apiUrl)return;try{await fetch(state.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,password:PASSWORD})})}catch(err){console.warn('Background sync failed',err)}}
