const DEMOS={
  paid:{email:'sofia@example.com',code:'ICH-SOFIA26',guest:'Sofía',fullName:'Sofía Martínez',language:'English',source:'Direct',status:'Confirmed',checkIn:'2026-09-18',checkOut:'2026-09-21',adults:4,children:2,total:13500,paid:13500,balance:0,paymentStatus:'Paid in full',current:false,transactions:[{label:'Reservation payment',date:'August 25, 2026',method:'Stripe',amount:13500,status:'Paid'}],requests:[]},
  balance:{email:'paul@example.com',code:'ICH-PAUL26',guest:'Paul',fullName:'Paul Meyer',language:'English',source:'Booking.com',status:'Confirmed',checkIn:'2026-09-07',checkOut:'2026-09-11',adults:4,children:0,total:18800,paid:14100,balance:4700,paymentStatus:'Balance due',current:false,transactions:[{label:'Deposit',date:'August 19, 2026',method:'Stripe',amount:14100,status:'Paid'}],requests:[{type:'Arrival question',text:'Can we arrive around 5:30 PM?',status:'Received',time:'Sent Aug 24'}]},
  current:{email:'daniel@example.com',code:'ICH-DANIEL26',guest:'Daniel',fullName:'Daniel Ruiz',language:'Español',source:'Direct',status:'Checked in',checkIn:'2026-08-21',checkOut:'2026-08-28',adults:6,children:2,total:31500,paid:31500,balance:0,paymentStatus:'Paid in full',current:true,transactions:[{label:'Reservation payment',date:'August 3, 2026',method:'Stripe',amount:31500,status:'Paid'}],requests:[{type:'House / amenity question',text:'Could we get two extra towels?',status:'Completed',time:'Sent Aug 24'}]}
};

const accessShell=document.getElementById('accessShell');
const identifyCard=document.getElementById('identifyCard');
const verificationCard=document.getElementById('verificationCard');
const portalApp=document.getElementById('portalApp');
const logoutButton=document.getElementById('logoutButton');
const accessForm=document.getElementById('accessForm');
const accessMessage=document.getElementById('accessMessage');
const emailInput=document.getElementById('guestEmail');
const codeInput=document.getElementById('reservationCode');
const toast=document.getElementById('portalToast');
let toastTimer;
let activeDemo=null;

const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n||0));
const parseDate=s=>new Date(`${s}T12:00:00`);
const fmt=s=>new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}).format(parseDate(s));
const fmtShort=s=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(parseDate(s));
const nights=r=>Math.round((parseDate(r.checkOut)-parseDate(r.checkIn))/86400000);
const guests=r=>r.adults+r.children;
function showToast(message){clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function normalizeCode(value){return String(value||'').trim().toUpperCase()}
function setVerifiedSession(enabled){if(enabled&&activeDemo)sessionStorage.setItem('ichkiichpan-guest-demo',activeDemo.code);else sessionStorage.removeItem('ichkiichpan-guest-demo')}
function findDemo(email,code){return Object.values(DEMOS).find(r=>r.email===email&&r.code===code)}
function openVerification(email){identifyCard.hidden=true;verificationCard.hidden=false;document.getElementById('verificationEmail').textContent=email}
function showView(view){document.querySelectorAll('.portal-view').forEach(section=>{const active=section.dataset.view===view;section.hidden=!active;section.classList.toggle('active',active)});document.querySelectorAll('[data-portal-view]').forEach(button=>button.classList.toggle('active',button.dataset.portalView===view));const mobile=document.getElementById('mobileViewSelect');if(mobile)mobile.value=view;window.scrollTo({top:0,behavior:'smooth'})}
function renderRequests(){const wrap=document.getElementById('requestHistory');if(!activeDemo.requests.length){wrap.innerHTML='<div class="empty-request"><strong>No open requests.</strong><p>Anything you send here will be linked only to this reservation.</p></div>';return}wrap.innerHTML=activeDemo.requests.map(r=>`<div class="request-item"><div><span>${r.time}</span><strong>${r.type}</strong><p>${r.text}</p></div><em>${r.status}</em></div>`).join('')}
function renderPayments(){document.getElementById('paymentTotal').textContent=money(activeDemo.total);document.getElementById('paymentPaid').textContent=money(activeDemo.paid);document.getElementById('paymentBalance').textContent=money(activeDemo.balance);document.getElementById('paymentBalanceCaption').textContent=activeDemo.balance?'Outstanding balance':'Nothing due';const status=document.getElementById('paymentPageStatus');status.textContent=activeDemo.paymentStatus;status.classList.toggle('paid',!activeDemo.balance);document.getElementById('overviewPaymentStatus').textContent=activeDemo.paymentStatus;document.getElementById('overviewPaymentStatus').classList.toggle('paid',!activeDemo.balance);document.getElementById('overviewBalance').textContent=money(activeDemo.balance);const list=document.getElementById('transactionList');list.innerHTML=activeDemo.transactions.map(t=>`<div class="transaction-row"><div><span class="transaction-icon">✓</span><div><strong>${t.label}</strong><small>${t.date} · ${t.method}</small></div></div><div><strong>${money(t.amount)}</strong><small>${t.status}</small></div></div>`).join('');document.getElementById('transactionCount').textContent=`${activeDemo.transactions.length} transaction${activeDemo.transactions.length===1?'':'s'}`;const pay=document.getElementById('payBalanceButton');pay.disabled=activeDemo.balance<=0;pay.classList.toggle('disabled-action',activeDemo.balance<=0);pay.textContent=activeDemo.balance?`Pay balance · ${money(activeDemo.balance)}`:'Paid in full'}
function renderPortal(){const r=activeDemo;document.getElementById('sidebarGuestName').textContent=r.guest;document.getElementById('sidebarReservationCode').textContent=r.code;document.getElementById('overviewStatus').textContent=r.status;document.getElementById('reservationStatus').textContent=r.status;document.getElementById('overviewKicker').textContent=r.current?'Your current stay':'Your upcoming stay';document.getElementById('overviewCountdown').textContent=r.current?'You are currently at Ichkiichpan':'Your stay is coming up';document.getElementById('overviewDates').textContent=`${fmtShort(r.checkIn)} — ${fmtShort(r.checkOut)}, 2026`;document.getElementById('overviewGuests').textContent=guests(r);document.getElementById('overviewNights').textContent=nights(r);document.getElementById('overviewCheckIn').textContent=fmtShort(r.checkIn);document.getElementById('reservationCodeDisplay').textContent=r.code;document.getElementById('reservationCheckIn').textContent=fmt(r.checkIn);document.getElementById('reservationCheckOut').textContent=fmt(r.checkOut);document.getElementById('reservationNights').textContent=`${nights(r)} nights`;document.getElementById('reservationGuests').textContent=`${r.adults} adults · ${r.children} children`;document.getElementById('reservationSource').textContent=r.source;document.getElementById('reservationGuestName').textContent=r.fullName;document.getElementById('reservationGuestEmail').textContent=r.email.replace(/(.{2}).+(@.+)/,'$1••••$2');document.getElementById('reservationLanguage').textContent=r.language;document.getElementById('arrivalCheckIn').textContent=fmtShort(r.checkIn);document.getElementById('arrivalCheckOut').textContent=fmtShort(r.checkOut);document.getElementById('arrivalTitle').textContent=r.current?'While you are here.':'Before you arrive.';document.getElementById('arrivalAvailability').textContent=r.current?'Available now':'Available before check-in';document.getElementById('arrivalCopy').textContent=r.current?'Your stay is active. Access and stay information is available here throughout your visit.':'Exact property access instructions, contact details and entry information can be released here shortly before arrival so they are not exposed publicly.';document.getElementById('accessInstructionIcon').textContent=r.current?'✓':'🔒';document.getElementById('accessInstructionTitle').textContent=r.current?'Access information available':'Access instructions are protected';document.getElementById('accessInstructionText').textContent=r.current?'Demo: the live portal would display the guest-specific access instructions here.':'Sensitive check-in instructions become visible only within the configured arrival window.';renderPayments();renderRequests()}
function openPortal(){if(!activeDemo)return;setVerifiedSession(true);renderPortal();accessShell.hidden=true;portalApp.hidden=false;logoutButton.hidden=false;showView('overview');window.scrollTo({top:0,behavior:'smooth'})}
function returnToLogin(){setVerifiedSession(false);activeDemo=null;portalApp.hidden=true;accessShell.hidden=false;identifyCard.hidden=false;verificationCard.hidden=true;logoutButton.hidden=true;accessMessage.textContent='';window.scrollTo({top:0,behavior:'smooth'})}

accessForm?.addEventListener('submit',event=>{event.preventDefault();if(!accessForm.reportValidity())return;const email=emailInput.value.trim().toLowerCase();const code=normalizeCode(codeInput.value);const found=findDemo(email,code);if(!found){accessMessage.textContent='Demo reservation not found. Choose one of the demo reservations below.';return}activeDemo=found;accessMessage.textContent='';openVerification(email)});
document.querySelectorAll('[data-demo-reservation]').forEach(button=>button.addEventListener('click',()=>{const r=DEMOS[button.dataset.demoReservation];emailInput.value=r.email;codeInput.value=r.code;accessMessage.textContent=`Loaded ${r.fullName} · ${r.paymentStatus}.`}));
document.getElementById('openDemoLinkButton')?.addEventListener('click',openPortal);
document.getElementById('backToLoginButton')?.addEventListener('click',()=>{verificationCard.hidden=true;identifyCard.hidden=false});
logoutButton?.addEventListener('click',returnToLogin);
document.querySelectorAll('[data-portal-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.portalView)));
document.querySelectorAll('[data-go-view]').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.goView)));
document.getElementById('mobileViewSelect')?.addEventListener('change',event=>showView(event.target.value));
document.getElementById('copyCodeButton')?.addEventListener('click',()=>showToast(`Reservation code: ${activeDemo.code}`));
document.getElementById('saveArrivalButton')?.addEventListener('click',()=>showToast('Arrival time saved for this demo.'));
document.getElementById('receiptButton')?.addEventListener('click',()=>showToast('A real Stripe receipt would open here.'));
document.getElementById('payBalanceButton')?.addEventListener('click',()=>{if(!activeDemo||activeDemo.balance<=0)return;showToast(`Demo Stripe checkout for ${money(activeDemo.balance)} would open here.`)});
document.getElementById('requestForm')?.addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);activeDemo.requests.unshift({type:data.get('type'),text:data.get('message'),status:'Received',time:'Sent just now'});renderRequests();document.getElementById('requestMessage').textContent='Request received in the demo.';form.reset();showToast('Request received.');});
const saved=sessionStorage.getItem('ichkiichpan-guest-demo');if(saved){activeDemo=Object.values(DEMOS).find(r=>r.code===saved)||null;if(activeDemo)openPortal();}