const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const ownerLogin=$('#ownerLogin'),ownerApp=$('#ownerApp');
const reservations=[
{id:'ICH-260821',guest:'Daniel Ruiz',source:'Direct',checkIn:'2026-08-21',checkOut:'2026-08-28',guests:8,gross:31500,balance:0,status:'Current',confirmation:'ICH-260821'},
{id:'AIR-84319',guest:'Mariana Torres',source:'Airbnb',checkIn:'2026-08-30',checkOut:'2026-09-04',guests:6,gross:22500,balance:0,status:'Upcoming',confirmation:'HM43Q7'},
{id:'BKG-11942',guest:'Paul Meyer',source:'Booking.com',checkIn:'2026-09-07',checkOut:'2026-09-11',guests:4,gross:18800,balance:4700,status:'Upcoming',confirmation:'428851942'},
{id:'VRB-77410',guest:'Andrea Gómez',source:'Vrbo',checkIn:'2026-09-14',checkOut:'2026-09-19',guests:10,gross:24750,balance:0,status:'Upcoming',confirmation:'HA-VR77410'},
{id:'DIR-9021',guest:'Sofia Hernández',source:'Direct',checkIn:'2026-09-23',checkOut:'2026-09-27',guests:5,gross:18400,balance:9200,status:'Upcoming',confirmation:'ICH-260923'}
];
const calendarBlocks=[{start:'2026-08-21',end:'2026-08-28',reservationId:'ICH-260821'},{start:'2026-08-30',end:'2026-09-04',reservationId:'AIR-84319'},{start:'2026-09-07',end:'2026-09-11',reservationId:'BKG-11942'},{start:'2026-09-14',end:'2026-09-19',reservationId:'VRB-77410'},{start:'2026-09-23',end:'2026-09-27',reservationId:'DIR-9021'},{start:'2026-10-02',end:'2026-10-05',reservationId:null,label:'Imported calendar block'}];
const emailIntake=[
{id:'mail1',source:'Booking.com',guest:'Paul Meyer',confirmation:'428851942',dates:'Sep 7–11',status:'Matched',detail:'Exact confirmation + dates matched to existing reservation.'},
{id:'mail2',source:'Airbnb',guest:'Luis Navarro',confirmation:'HMA92P',dates:'Oct 2–5',status:'Review',detail:'Dates match an existing calendar-only block. Guest details can complete the blocked stay.'},
{id:'mail3',source:'Vrbo',guest:'Julia Chen',confirmation:'HA-99241',dates:'Oct 12–16',status:'New',detail:'No existing block found. Ready to create a new reservation after owner review.'}
];
const reconciliation=[
{id:'rec1',incoming:'Airbnb · Luis Navarro',dates:'Oct 2–5',calendar:'Calendar block · Oct 2–5',confidence:'96%',status:'Review'},
{id:'rec2',incoming:'Booking · Paul Meyer',dates:'Sep 7–11',calendar:'Booking reservation · Sep 7–11',confidence:'100%',status:'Matched'},
{id:'rec3',incoming:'Vrbo · Julia Chen',dates:'Oct 12–16',calendar:'No block found',confidence:'—',status:'New'}
];
let calendarCursor=new Date(2026,7,1);
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function localDate(s){return new Date(`${s}T12:00:00`)}
function sourceClass(s){return s==='Airbnb'?'airbnb':s==='Booking.com'?'booking':s==='Vrbo'?'vrbo':'direct'}
function toast(msg){const el=$('#ownerToast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2200)}

$('#ownerLoginForm').addEventListener('submit',e=>{e.preventDefault();ownerLogin.hidden=true;ownerApp.hidden=false;sessionStorage.setItem('ichOwnerDemo','1');renderAll()});
$('#ownerLogout').addEventListener('click',()=>{sessionStorage.removeItem('ichOwnerDemo');location.reload()});
if(sessionStorage.getItem('ichOwnerDemo')==='1'){ownerLogin.hidden=true;ownerApp.hidden=false;renderAll()}

function switchView(name){$$('.owner-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('[data-view-panel]').forEach(p=>{const active=p.dataset.viewPanel===name;p.hidden=!active;p.classList.toggle('active',active)});const labels={overview:['PROPERTY OVERVIEW','Good evening.'],calendar:['UNIFIED AVAILABILITY','Calendar'],reservations:['ALL CHANNELS','Reservations'],intake:['RESERVATION INTAKE','Capture & reconcile'],guests:['GUEST HISTORY','Guests'],operations:['TODAY + NEXT','Operations'],financials:['PROPERTY ECONOMICS','Financials'],performance:['REVENUE MANAGEMENT','Performance'],marketing:['DIRECT DEMAND','Marketing'],settings:['SYSTEM','Settings']};$('#viewEyebrow').textContent=labels[name][0];$('#viewTitle').textContent=labels[name][1];if(innerWidth<901)$('#ownerSidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
$$('.owner-nav button').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));$('#sidebarToggle').addEventListener('click',()=>$('#ownerSidebar').classList.toggle('open'));
$('#quickAdd').addEventListener('click',()=>toast('Reservation creation form will connect to the live reservation store later.'));

function renderOverview(){
 const metrics=[['Occupancy','71%','+9 pts vs July','up'],['Gross revenue',money(85300),'+14% vs July','up'],['ADR',money(4062),'+3% vs July','up'],['Rev / available night',money(2881),'+11% vs July','up'],['Operating profit',money(51200),'60.0% margin','up'],['Direct booking share','37%','+8 pts vs July','up']];
 $('#overviewMetrics').innerHTML=metrics.map(([l,v,h,c])=>`<div class="metric-tile"><span>${l}</span><strong>${v}</strong><small class="${c}">${h}</small></div>`).join('');
 $('#attentionList').innerHTML=[['!','Balance due before arrival','Paul Meyer · '+money(4700)+' outstanding'],['↻','Reservation needs reconciliation','Airbnb email matches Oct 2–5 calendar block'],['✓','Cleaning confirmation needed','Aug 30 arrival · cleaning scheduled, not yet confirmed']].map(x=>`<div class="attention-item"><div class="attention-icon">${x[0]}</div><div><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join('');
 $('#channelBars').innerHTML=[['Direct',31500,37],['Airbnb',22500,26],['Booking.com',18800,22],['Vrbo',12500,15]].map(([n,v,p])=>`<div class="channel-row"><span>${n}</span><div class="channel-track"><i style="width:${p}%"></i></div><strong>${p}%</strong></div>`).join('');
 $('#profitStack').innerHTML=[['Gross reservation revenue',85300],['Platform commissions',-6900],['Cleaning & laundry',-6200],['Utilities / fuel',-5600],['Supplies & maintenance',-4400],['Operating profit',62200]].map((x,i)=>`<div class="profit-line ${i===5?'total':''}"><span>${x[0]}</span><strong>${x[1]<0?'− ':''}${money(Math.abs(x[1]))}</strong></div>`).join('');
 renderMiniCalendar();
}
function bookingForDate(dateIso){return reservations.find(r=>dateIso>=r.checkIn&&dateIso<r.checkOut)}
function blockForDate(dateIso){return calendarBlocks.find(b=>dateIso>=b.start&&dateIso<b.end)}
function renderMiniCalendar(){const year=2026,month=7,first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="weekday">${d}</div>`).join('');for(let i=0;i<35;i++){const d=new Date(start);d.setDate(start.getDate()+i);const di=iso(d),r=bookingForDate(di),b=blockForDate(di);const cls=r?sourceClass(r.source)+'-fill':b?'block-fill':'';html+=`<div class="mini-day ${d.getMonth()!==month?'outside':''}">${d.getDate()}${r||b?`<div class="mini-booking ${cls}"></div>`:''}</div>`}$('#miniCalendar').innerHTML=html}
function renderFullCalendar(){const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth();$('#calendarMonthTitle').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(calendarCursor);const first=new Date(year,month,1),start=new Date(year,month,1-first.getDay());let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="weekday">${d}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const di=iso(d),r=bookingForDate(di),b=blockForDate(di);let chip='';if(r)chip=`<button class="full-booking ${sourceClass(r.source)}-fill" data-res-id="${r.id}">${r.guest}</button>`;else if(b)chip=`<button class="full-booking block-fill">Blocked</button>`;html+=`<div class="full-day ${d.getMonth()!==month?'outside':''}"><span>${d.getDate()}</span>${chip}</div>`}$('#fullCalendar').innerHTML=html;$$('[data-res-id]').forEach(b=>b.addEventListener('click',()=>openReservation(b.dataset.resId)))}
$('#calendarPrev').addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderFullCalendar()});$('#calendarNext').addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderFullCalendar()});
function renderGaps(){$('#gapGrid').innerHTML=[['Aug 28–30','2 nights','Short vacancy between direct stay and Airbnb arrival.'],['Sep 4–7','3 nights','Potential short-stay opportunity.'],['Sep 19–23','4 nights','Largest open September window.']].map(x=>`<div class="gap-card"><span>Open window</span><strong>${x[0]} · ${x[1]}</strong><p>${x[2]}</p></div>`).join('')}
function renderReservations(){const q=($('#reservationSearch')?.value||'').toLowerCase(),f=$('#reservationFilter')?.value||'all';const list=reservations.filter(r=>{const text=`${r.guest} ${r.source} ${r.confirmation}`.toLowerCase();if(q&&!text.includes(q))return false;if(f==='upcoming'&&r.status!=='Upcoming')return false;if(f==='current'&&r.status!=='Current')return false;if(f==='balance'&&r.balance<=0)return false;return true});$('#reservationRows').innerHTML=list.map(r=>`<tr data-row-res="${r.id}"><td><strong>${r.guest}</strong><br><span>${r.confirmation}</span></td><td><span class="channel-badge ${sourceClass(r.source)}">${r.source}</span></td><td>${r.checkIn} → ${r.checkOut}</td><td>${r.guests}</td><td>${money(r.gross)}</td><td>${money(r.balance)}</td><td>${r.status}</td></tr>`).join('');$$('[data-row-res]').forEach(row=>row.addEventListener('click',()=>openReservation(row.dataset.rowRes)))}
$('#reservationSearch').addEventListener('input',renderReservations);$('#reservationFilter').addEventListener('change',renderReservations);
function openReservation(id){const r=reservations.find(x=>x.id===id);if(!r)return;$('#dialogContent').innerHTML=`<div class="dialog-inner"><p class="eyebrow">${r.source}</p><h3>${r.guest}</h3><div class="dialog-grid"><div><span>Confirmation</span><strong>${r.confirmation}</strong></div><div><span>Status</span><strong>${r.status}</strong></div><div><span>Check-in</span><strong>${r.checkIn}</strong></div><div><span>Check-out</span><strong>${r.checkOut}</strong></div><div><span>Guests</span><strong>${r.guests}</strong></div><div><span>Gross revenue</span><strong>${money(r.gross)}</strong></div><div><span>Balance</span><strong>${money(r.balance)}</strong></div><div><span>Source</span><strong>${r.source}</strong></div></div></div>`;$('#detailDialog').showModal()}
$('#dialogClose').addEventListener('click',()=>$('#detailDialog').close());
function renderIntake(){const matched=emailIntake.filter(x=>x.status==='Matched').length,review=emailIntake.filter(x=>x.status==='Review').length,newCount=emailIntake.filter(x=>x.status==='New').length;$('#intakeSummary').innerHTML=[['Detected emails',emailIntake.length],['Auto-matched',matched],['Needs review',review],['New reservation',newCount]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#emailIntakeList').innerHTML=emailIntake.map(x=>`<div class="intake-item"><div class="intake-item-head"><strong>${x.source} · ${x.guest}</strong><span class="match-pill ${x.status==='Review'?'review':x.status==='New'?'conflict':''}">${x.status}</span></div><p>${x.dates} · ${x.confirmation}</p><p>${x.detail}</p></div>`).join('');$('#reconciliationList').innerHTML=reconciliation.map(x=>`<div class="reconciliation-row" data-rec="${x.id}"><div><strong>${x.incoming}</strong><br><span>${x.dates}</span></div><div><strong>${x.calendar}</strong></div><div><span>Match confidence</span><br><strong>${x.confidence}</strong></div><div class="reconcile-actions">${x.status==='Review'?'<button class="tiny-button primary" data-match>Match</button><button class="tiny-button" data-separate>Keep separate</button>':x.status==='New'?'<button class="tiny-button primary" data-create>Create</button>':`<span class="match-pill">${x.status}</span>`}</div></div>`).join('');$$('[data-match]').forEach(b=>b.addEventListener('click',e=>{const row=e.target.closest('[data-rec]');row.querySelector('.reconcile-actions').innerHTML='<span class="match-pill">Matched</span>';toast('Reservation matched to the existing calendar block.')}));$$('[data-separate]').forEach(b=>b.addEventListener('click',()=>toast('Kept as separate records for owner review.')));$$('[data-create]').forEach(b=>b.addEventListener('click',e=>{e.target.closest('[data-rec]').querySelector('.reconcile-actions').innerHTML='<span class="match-pill">Created</span>';toast('Demo reservation created from incoming data.')}))}
$('#reservationUpload').addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;$('#uploadStatus').textContent=`${f.name} selected · Demo import scanned 3 reservation rows · 2 matched · 1 needs review.`;toast('Reservation file analyzed in demo mode.')});
function renderGuests(){$('#guestGrid').innerHTML=[['Daniel Ruiz','Direct','2 stays','12 nights',63000],['Mariana Torres','Airbnb','1 stay','5 nights',22500],['Andrea Gómez','Vrbo','1 stay','5 nights',24750],['Paul Meyer','Booking.com','1 stay','4 nights',18800],['Sofia Hernández','Direct','1 stay','4 nights',18400]].map(x=>`<article class="guest-card"><p class="eyebrow">${x[1]}</p><h3>${x[0]}</h3><p>Guest profile and private owner history.</p><div class="guest-stats"><div><span>History</span><strong>${x[2]}</strong></div><div><span>Total nights</span><strong>${x[3]}</strong></div><div><span>Lifetime value</span><strong>${money(x[4])}</strong></div></div></article>`).join('')}
function renderOperations(){$('#operationsGrid').innerHTML=[['Current stay','Daniel Ruiz','Checkout Aug 28 · 8 guests',[['Guest status','In house'],['Balance','Paid'],['Open requests','None']]],['Turnover','Aug 28 → Aug 30','2-night window',[['Checkout','11:00 AM'],['Cleaning','Scheduled'],['Next arrival','Aug 30 · 4:30 PM']]],['Needs action','3 items','Owner queue',[['Payment','Paul Meyer · '+money(4700)],['Reconciliation','Oct 2–5'],['Cleaning','Aug 30 confirmation']]]].map(x=>`<article class="operation-card"><p class="eyebrow">${x[0]}</p><h3>${x[1]}</h3><p>${x[2]}</p><div class="operation-lines">${x[3].map(y=>`<div><span>${y[0]}</span><strong>${y[1]}</strong></div>`).join('')}</div></article>`).join('')}
function renderFinancials(){const metrics=[['Gross revenue',85300,'+14%'],['Net after channel fees',78400,'+12%'],['Operating costs',16200,'−3%'],['Operating profit',62200,'+18%'],['Margin','72.9%','+2.4 pts'],['Outstanding balances',13900,'2 reservations']];$('#financialMetrics').innerHTML=metrics.map(x=>`<div class="metric-tile"><span>${x[0]}</span><strong>${typeof x[1]==='number'?money(x[1]):x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#financialWaterfall').innerHTML=[['Gross revenue',85300],['Platform commissions',-6900],['Cleaning',-3600],['Laundry',-2600],['Utilities / fuel',-5600],['Maintenance & supplies',-4400],['Operating profit',62200]].map((x,i,a)=>`<div class="profit-line ${i===a.length-1?'total':''}"><span>${x[0]}</span><strong>${x[1]<0?'− ':''}${money(Math.abs(x[1]))}</strong></div>`).join('');$('#expenseBars').innerHTML=[['Platform fees',6900,43],['Utilities / fuel',5600,35],['Maintenance',2800,17],['Cleaning',3600,22],['Laundry',2600,16]].map(x=>`<div class="channel-row"><span>${x[0]}</span><div class="channel-track"><i style="width:${x[2]}%"></i></div><strong>${money(x[1])}</strong></div>`).join('')}
function renderPerformance(){$('#performanceGrid').innerHTML=[['Occupancy','71%','+9 pts vs July'],['ADR',money(4062),'+3% vs July'],['Rev / available night',money(2881),'+11% vs July'],['Avg stay','4.2 nights','+0.4 nights'],['Booking lead time','26 days','+3 days'],['Direct share','37%','+8 pts']].map(x=>`<article class="performance-card"><p class="eyebrow">${x[0]}</p><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');$('#comparisonTable').innerHTML=`<div class="comparison-row head"><span>Metric</span><span>July</span><span>August</span><span>Change</span></div>${[['Occupancy','62%','71%','+9 pts'],['Gross revenue',money(74800),money(85300),'+14%'],['ADR',money(3940),money(4062),'+3%'],['Direct share','29%','37%','+8 pts'],['Avg stay','3.8','4.2','+0.4']].map(x=>`<div class="comparison-row"><strong>${x[0]}</strong><span>${x[1]}</span><span>${x[2]}</span><strong>${x[3]}</strong></div>`).join('')}`}
function renderAll(){const today=new Date();$('#todayLabel').textContent=new Intl.DateTimeFormat('en-CA',{weekday:'long',month:'short',day:'numeric'}).format(today);renderOverview();renderFullCalendar();renderGaps();renderReservations();renderIntake();renderGuests();renderOperations();renderFinancials();renderPerformance()}
