const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(Number(n||0));
const dateOnly=s=>new Date(`${s}T12:00:00`);
const fmt=s=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(dateOnly(s));
const fmtLong=s=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(dateOnly(s));
const days=(a,b)=>Math.round((dateOnly(b)-dateOnly(a))/86400000);
const today='2026-08-25';
const ownerLogin=$('#ownerLogin'),ownerApp=$('#ownerApp'),detailDialog=$('#detailDialog'),dialogContent=$('#dialogContent');
const reservations=[
{id:'ICH-260821',guest:'Daniel Ruiz',email:'daniel@example.com',source:'Direct',checkIn:'2026-08-21',checkOut:'2026-08-28',guests:8,gross:31500,balance:0,status:'Current',confirmation:'ICH-260821',commission:0,taxes:0,cleaning:1400,laundry:1000,otherCost:2800,payment:'Paid',cleaningStatus:'Completed',arrival:'4:00 PM',notes:'Current guest. Extra towel request completed.'},
{id:'AIR-84319',guest:'Mariana Torres',email:'mariana@example.com',source:'Airbnb',checkIn:'2026-08-30',checkOut:'2026-09-04',guests:6,gross:22500,balance:0,status:'Upcoming',confirmation:'HM43Q7',commission:3375,taxes:0,cleaning:1400,laundry:1000,otherCost:2000,payment:'Paid',cleaningStatus:'Scheduled',arrival:'4:30 PM',notes:'Family trip. Arrival confirmed.'},
{id:'BKG-11942',guest:'Paul Meyer',email:'paul@example.com',source:'Booking.com',checkIn:'2026-09-07',checkOut:'2026-09-11',guests:4,gross:18800,balance:4700,status:'Upcoming',confirmation:'428851942',commission:2820,taxes:0,cleaning:1400,laundry:800,otherCost:1600,payment:'Partial',cleaningStatus:'Pending',arrival:'5:30 PM',notes:'Balance due before arrival.'},
{id:'VRB-77410',guest:'Andrea Gómez',email:'andrea@example.com',source:'Vrbo',checkIn:'2026-09-14',checkOut:'2026-09-19',guests:10,gross:24750,balance:0,status:'Upcoming',confirmation:'HA-VR77410',commission:2970,taxes:0,cleaning:1400,laundry:1000,otherCost:2200,payment:'Paid',cleaningStatus:'Pending',arrival:'Not set',notes:'Large group. Verify guest count before arrival.'},
{id:'DIR-9021',guest:'Sofia Hernández',email:'sofia.h@example.com',source:'Direct',checkIn:'2026-09-23',checkOut:'2026-09-27',guests:5,gross:18400,balance:9200,status:'Upcoming',confirmation:'ICH-260923',commission:662,taxes:0,cleaning:1400,laundry:800,otherCost:1600,payment:'Partial',cleaningStatus:'Pending',arrival:'Not set',notes:'Direct Stripe reservation. Second payment outstanding.'},
{id:'AIR-91022',guest:'Luis Navarro',email:'luis@example.com',source:'Airbnb',checkIn:'2026-10-02',checkOut:'2026-10-05',guests:2,gross:12600,balance:0,status:'Upcoming',confirmation:'HMA92P',commission:1890,taxes:0,cleaning:1400,laundry:400,otherCost:1200,payment:'Paid',cleaningStatus:'Pending',arrival:'Not set',notes:'Matched from Airbnb email to prior calendar-only block.'},
{id:'BKG-22051',guest:'Julia Chen',email:'julia@example.com',source:'Booking.com',checkIn:'2026-10-12',checkOut:'2026-10-16',guests:7,gross:19600,balance:4900,status:'Upcoming',confirmation:'5220051',commission:2940,taxes:0,cleaning:1400,laundry:1000,otherCost:1700,payment:'Partial',cleaningStatus:'Pending',arrival:'Not set',notes:'New reservation imported from platform email.'},
{id:'VRB-88220',guest:'Thomas Reed',email:'thomas@example.com',source:'Vrbo',checkIn:'2026-07-18',checkOut:'2026-07-22',guests:6,gross:17200,balance:0,status:'Completed',confirmation:'VR-88220',commission:2064,taxes:0,cleaning:1400,laundry:1000,otherCost:1700,payment:'Paid',cleaningStatus:'Completed',arrival:'Completed',notes:'Completed stay.'}
];
const calendarBlocks=[...reservations.filter(r=>r.status!=='Completed').map(r=>({start:r.checkIn,end:r.checkOut,reservationId:r.id})),{start:'2026-10-22',end:'2026-10-25',reservationId:null,label:'Calendar-only block'}];
const emailIntake=[{id:'mail1',source:'Booking.com',guest:'Paul Meyer',confirmation:'428851942',dates:'Sep 7–11',status:'Matched',detail:'Exact confirmation + dates matched to existing reservation.'},{id:'mail2',source:'Airbnb',guest:'Luis Navarro',confirmation:'HMA92P',dates:'Oct 2–5',status:'Review',detail:'Dates matched an existing calendar-only block. Demo shows this as recently reconciled.'},{id:'mail3',source:'Booking.com',guest:'Julia Chen',confirmation:'5220051',dates:'Oct 12–16',status:'New',detail:'No pre-existing block. Ready to create after owner review.'}];
const reconciliation=[{id:'rec1',incoming:'Airbnb · Luis Navarro',dates:'Oct 2–5',calendar:'Prior calendar block · Oct 2–5',confidence:'96%',status:'Review'},{id:'rec2',incoming:'Booking · Paul Meyer',dates:'Sep 7–11',calendar:'Booking reservation · Sep 7–11',confidence:'100%',status:'Matched'},{id:'rec3',incoming:'Booking · Julia Chen',dates:'Oct 12–16',calendar:'No block found',confidence:'—',status:'New'}];
let calendarCursor=new Date(2026,7,1),toastTimer;

function sourceClass(s){return s==='Airbnb'?'airbnb':s==='Booking.com'?'booking':s==='Vrbo'?'vrbo':'direct'}
function stayNights(r){return days(r.checkIn,r.checkOut)}
function adr(r){return r.gross/Math.max(1,stayNights(r))}
function contribution(r){return r.gross-r.commission-r.cleaning-r.laundry-r.otherCost-r.taxes}
function contributionMargin(r){return r.gross?contribution(r)/r.gross:0}
function showToast(msg){const t=$('#ownerToast');clearTimeout(toastTimer);t.textContent=msg;t.hidden=false;t.classList.add('show');toastTimer=setTimeout(()=>{t.classList.remove('show');t.hidden=true},2300)}
function currentMonthReservations(){return reservations.filter(r=>r.checkIn.startsWith('2026-08')&&r.status!=='Cancelled')}
function switchView(name){$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('[data-view-panel]').forEach(v=>{const on=v.dataset.viewPanel===name;v.hidden=!on;v.classList.toggle('active',on)});const titles={overview:['PROPERTY OVERVIEW','Good evening.'],calendar:['UNIFIED AVAILABILITY','Calendar'],reservations:['ALL CHANNELS','Reservations'],intake:['RESERVATION INTAKE','Capture & reconcile'],guests:['GUEST HISTORY','Guests'],operations:['TODAY + NEXT','Operations'],financials:['PROPERTY ECONOMICS','Financials'],performance:['REVENUE MANAGEMENT','Performance'],marketing:['DIRECT DEMAND','Marketing'],settings:['SYSTEM','Settings']};$('#viewEyebrow').textContent=titles[name][0];$('#viewTitle').textContent=titles[name][1];if(name==='calendar')renderCalendar();if(name==='reservations')renderReservations();window.scrollTo({top:0,behavior:'smooth'})}
function openApp(){ownerLogin.hidden=true;ownerApp.hidden=false;renderAll()}
$('#ownerLoginForm')?.addEventListener('submit',e=>{e.preventDefault();openApp()});$('#ownerLogout')?.addEventListener('click',()=>{ownerApp.hidden=true;ownerLogin.hidden=false});$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.go)));$('#sidebarToggle')?.addEventListener('click',()=>$('#ownerSidebar').classList.toggle('open'));

function renderOverview(){const august=currentMonthReservations();const occupied=august.reduce((s,r)=>s+stayNights(r),0);const gross=august.reduce((s,r)=>s+r.gross,0);const direct=august.filter(r=>r.source==='Direct').reduce((s,r)=>s+r.gross,0);const costs=august.reduce((s,r)=>s+(r.commission+r.cleaning+r.laundry+r.otherCost+r.taxes),0);const metrics=[['Occupancy',`${Math.round(occupied/31*100)}%`,'↑ 8 pts vs July','up'],['Revenue',money(gross),'↑ 14% vs July','up'],['ADR',money(gross/Math.max(1,occupied)),'↑ 5% vs July','up'],['RevPAN',money(gross/31),'Revenue / available night',''],['Operating profit',money(gross-costs),`${Math.round((gross-costs)/gross*100)}% margin`,'up'],['Direct share',`${Math.round(direct/gross*100)}%`,'Lower commission mix','up']];$('#overviewMetrics').innerHTML=metrics.map(m=>`<div class="metric-tile"><span>${m[0]}</span><strong>${m[1]}</strong><small class="${m[3]}">${m[2]}</small></div>`).join('');$('#attentionList').innerHTML=[['Payment due','Paul Meyer · '+money(4700)+' outstanding'],['Cleaning pending','Vrbo arrival · Sep 14'],['Short gap','Aug 28–30 · 2 nights open']].map(x=>`<div class="attention-item"><span class="attention-icon">!</span><div><strong>${x[0]}</strong><span>${x[1]}</span></div></div>`).join('');renderMiniCalendar();renderChannelBars();renderProfitStack()}
function renderChannelBars(){const data=[['Direct',31500],['Airbnb',22500],['Booking.com',0],['Vrbo',0]],max=31500;$('#channelBars').innerHTML=data.map(([n,v])=>`<div class="channel-row"><span>${n}</span><div class="channel-track"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join('')}
function renderProfitStack(){const august=currentMonthReservations(),gross=august.reduce((s,r)=>s+r.gross,0),platform=august.reduce((s,r)=>s+r.commission,0),ops=august.reduce((s,r)=>s+r.cleaning+r.laundry+r.otherCost,0),profit=gross-platform-ops;$('#profitStack').innerHTML=[['Gross revenue',gross],['Platform fees',-platform],['Variable operating costs',-ops],['Operating profit',profit]].map((x,i)=>`<div class="profit-line ${i===3?'total':''}"><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join('')}
function calendarData(year,month){const start=new Date(year,month,1-new Date(year,month,1).getDay()),arr=[];for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;arr.push({date:d,iso,bookings:reservations.filter(r=>r.status!=='Cancelled'&&r.status!=='Completed'&&iso>=r.checkIn&&iso<r.checkOut),blocks:calendarBlocks.filter(b=>!b.reservationId&&iso>=b.start&&iso<b.end)})}return arr}
function renderMiniCalendar(){const weekdays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#miniCalendar').innerHTML=weekdays.map(w=>`<div class="weekday">${w}</div>`).join('')+calendarData(2026,7).map(c=>`<div class="mini-day ${c.date.getMonth()!==7?'outside':''}">${c.date.getDate()}${c.bookings.slice(0,2).map(r=>`<div class="mini-booking ${sourceClass(r.source)}-fill"></div>`).join('')}</div>`).join('')}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$('#calendarMonthTitle').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(calendarCursor);const weekdays=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];$('#fullCalendar').innerHTML=weekdays.map(w=>`<div class="weekday">${w}</div>`).join('')+calendarData(y,m).map(c=>`<div class="full-day ${c.date.getMonth()!==m?'outside':''}"><strong>${c.date.getDate()}</strong>${c.bookings.map(r=>`<button class="full-booking ${sourceClass(r.source)}-fill" data-reservation-id="${r.id}">${r.guest}</button>`).join('')}${c.blocks.map(()=>`<div class="full-booking block-fill">Blocked</div>`).join('')}</div>`).join('');$('#gapGrid').innerHTML=[['Aug 28–30','2-night opening','Short-gap opportunity before Airbnb arrival.'],['Sep 4–7','3-night opening','Strong candidate for direct-booking promotion.'],['Sep 19–23','4-night opening','Could support standard minimum stay.']].map(g=>`<div class="gap-card"><span>${g[1]}</span><strong>${g[0]}</strong><p>${g[2]}</p></div>`).join('');bindReservationButtons()}
$('#calendarPrev')?.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()});$('#calendarNext')?.addEventListener('click',()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()});
function renderReservations(){const q=($('#reservationSearch')?.value||'').toLowerCase(),f=$('#reservationFilter')?.value||'all';const rows=reservations.filter(r=>{if(q&&!`${r.guest} ${r.confirmation} ${r.source}`.toLowerCase().includes(q))return false;if(f==='upcoming'&&r.status!=='Upcoming')return false;if(f==='current'&&r.status!=='Current')return false;if(f==='balance'&&r.balance<=0)return false;return true});$('#reservationRows').innerHTML=rows.map(r=>`<tr class="reservation-row" data-reservation-id="${r.id}"><td><strong>${r.guest}</strong><br><small>${r.confirmation}</small></td><td><span class="channel-badge ${sourceClass(r.source)}">${r.source}</span></td><td>${fmt(r.checkIn)}–${fmt(r.checkOut)}<br><small>${stayNights(r)} nights</small></td><td>${r.guests}</td><td>${money(r.gross)}</td><td>${money(r.balance)}</td><td>${r.status}</td></tr>`).join('');bindReservationButtons()}
$('#reservationSearch')?.addEventListener('input',renderReservations);$('#reservationFilter')?.addEventListener('change',renderReservations);
function openReservation(id){const r=reservations.find(x=>x.id===id);if(!r)return;dialogContent.innerHTML=`<div class="reservation-detail-demo"><p class="eyebrow">${r.source} · ${r.confirmation}</p><h2>${r.guest}</h2><p class="detail-subline">${fmtLong(r.checkIn)} → ${fmtLong(r.checkOut)} · ${stayNights(r)} nights · ${r.guests} guests</p><div class="detail-metrics"><div><span>Gross revenue</span><strong>${money(r.gross)}</strong></div><div><span>ADR</span><strong>${money(adr(r))}</strong></div><div><span>Contribution</span><strong>${money(contribution(r))}</strong></div><div><span>Margin</span><strong>${Math.round(contributionMargin(r)*100)}%</strong></div></div><div class="reservation-detail-grid"><section><h3>Guest & stay</h3><dl><div><dt>Email</dt><dd>${r.email}</dd></div><div><dt>Arrival</dt><dd>${r.arrival}</dd></div><div><dt>Payment</dt><dd>${r.payment}</dd></div><div><dt>Balance</dt><dd>${money(r.balance)}</dd></div><div><dt>Cleaning</dt><dd>${r.cleaningStatus}</dd></div></dl></section><section><h3>Reservation economics</h3><dl><div><dt>Gross</dt><dd>${money(r.gross)}</dd></div><div><dt>Platform / payment fees</dt><dd>− ${money(r.commission)}</dd></div><div><dt>Cleaning</dt><dd>− ${money(r.cleaning)}</dd></div><div><dt>Laundry</dt><dd>− ${money(r.laundry)}</dd></div><div><dt>Other variable costs</dt><dd>− ${money(r.otherCost)}</dd></div><div class="detail-total"><dt>Estimated contribution</dt><dd>${money(contribution(r))}</dd></div></dl></section></div><section class="detail-note"><h3>Owner notes</h3><p>${r.notes}</p></section><div class="demo-edit-controls"><label>Payment status<select id="demoPaymentStatus"><option ${r.payment==='Paid'?'selected':''}>Paid</option><option ${r.payment==='Partial'?'selected':''}>Partial</option><option ${r.payment==='Pending'?'selected':''}>Pending</option></select></label><label>Cleaning status<select id="demoCleaningStatus"><option ${r.cleaningStatus==='Pending'?'selected':''}>Pending</option><option ${r.cleaningStatus==='Scheduled'?'selected':''}>Scheduled</option><option ${r.cleaningStatus==='Completed'?'selected':''}>Completed</option></select></label><button class="primary-action" id="saveDemoReservation" type="button">Save demo changes</button></div></div>`;detailDialog.showModal();$('#saveDemoReservation').addEventListener('click',()=>{r.payment=$('#demoPaymentStatus').value;r.cleaningStatus=$('#demoCleaningStatus').value;if(r.payment==='Paid')r.balance=0;showToast('Demo reservation updated.');detailDialog.close();renderAll()})}
function bindReservationButtons(){$$('[data-reservation-id]').forEach(el=>{el.onclick=()=>openReservation(el.dataset.reservationId)})}
$('#dialogClose')?.addEventListener('click',()=>detailDialog.close());
function renderIntake(){$('#intakeSummary').innerHTML=[['Detected emails',3],['Auto matched',1],['Needs review',1],['New reservation',1]].map(x=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('#emailIntakeList').innerHTML=emailIntake.map(x=>`<div class="intake-item"><div class="intake-item-head"><strong>${x.source} · ${x.guest}</strong><span class="match-pill ${x.status==='Review'?'review':''}">${x.status}</span></div><p>${x.dates} · ${x.confirmation}</p><p>${x.detail}</p></div>`).join('');renderReconciliation()}
function renderReconciliation(){$('#reconciliationList').innerHTML=reconciliation.map(x=>`<div class="reconciliation-row"><div><strong>${x.incoming}</strong><span>${x.dates}</span></div><div><strong>${x.calendar}</strong></div><div><span>Confidence</span><strong>${x.confidence}</strong></div><div class="reconcile-actions">${x.status==='Review'?`<button class="tiny-button primary" data-reconcile="${x.id}" data-action="match">Match</button><button class="tiny-button" data-reconcile="${x.id}" data-action="separate">Keep separate</button>`:x.status==='New'?`<button class="tiny-button primary" data-reconcile="${x.id}" data-action="create">Create</button>`:`<span class="match-pill">Matched</span>`}</div></div>`).join('');$$('[data-reconcile]').forEach(b=>b.addEventListener('click',()=>{const item=reconciliation.find(x=>x.id===b.dataset.reconcile);item.status=b.dataset.action==='separate'?'Separate':'Matched';showToast(b.dataset.action==='create'?'Demo reservation created.':b.dataset.action==='match'?'Calendar block matched.':'Kept as separate records.');renderReconciliation()}))}
$('#reservationUpload')?.addEventListener('change',e=>{$('#uploadStatus').textContent=e.target.files[0]?`${e.target.files[0].name} loaded · demo import found 4 records, 3 matched and 1 needs review.`:'No file selected.'});
function renderGuests(){$('#guestGrid').innerHTML=reservations.filter(r=>r.status!=='Completed'||r.id==='VRB-88220').slice(0,6).map(r=>`<article class="owner-card guest-card" data-reservation-id="${r.id}"><span class="channel-badge ${sourceClass(r.source)}">${r.source}</span><h3>${r.guest}</h3><p>${r.email}</p><dl><div><dt>Stay</dt><dd>${fmt(r.checkIn)}–${fmt(r.checkOut)}</dd></div><div><dt>Value</dt><dd>${money(r.gross)}</dd></div></dl></article>`).join('');bindReservationButtons()}
function renderOperations(){$('#operationsGrid').innerHTML=[['Today','Daniel Ruiz in house','Checkout Aug 28 · 8 guests','Completed'],['Next turnover','Clean after Aug 28 checkout','2-night gap before next arrival','Scheduled'],['Payment','Paul Meyer balance due',money(4700)+' remaining','Needs action'],['Upcoming cleaning','Andrea Gómez · Sep 14','10 guests · Vrbo','Pending']].map(x=>`<article class="owner-card operation-card"><p class="eyebrow">${x[0]}</p><h3>${x[1]}</h3><p>${x[2]}</p><span class="match-pill ${x[3]==='Needs action'?'review':''}">${x[3]}</span></article>`).join('')}
function renderFinancials(){const all=reservations.filter(r=>r.status!=='Cancelled'),gross=all.reduce((s,r)=>s+r.gross,0),fees=all.reduce((s,r)=>s+r.commission,0),variable=all.reduce((s,r)=>s+r.cleaning+r.laundry+r.otherCost,0),balances=all.reduce((s,r)=>s+r.balance,0),profit=gross-fees-variable;$('#financialMetrics').innerHTML=[['Booked revenue',money(gross),'Mock portfolio'],['Outstanding',money(balances),'Across active stays'],['Variable costs',money(variable),'Reservation linked'],['Operating contribution',money(profit),`${Math.round(profit/gross*100)}% margin`],['Platform fees',money(fees),'Mock commissions'],['Avg booking',money(gross/all.length),'Per reservation']].map(x=>`<div class="metric-tile"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');$('#financialWaterfall').innerHTML=[['Booked revenue',gross],['Platform/payment fees',-fees],['Cleaning/laundry/variable',-variable],['Operating contribution',profit]].map((x,i)=>`<div class="waterfall-row ${i===3?'total':''}"><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join('');$('#expenseBars').innerHTML=[['Cleaning',11200],['Laundry',7000],['Other variable',14800],['Platform fees',16721]].map(x=>`<div class="channel-row"><span>${x[0]}</span><div class="channel-track"><i style="width:${x[1]/16721*100}%"></i></div><strong>${money(x[1])}</strong></div>`).join('')}
function renderPerformance(){const active=reservations.filter(r=>r.status!=='Cancelled'&&r.status!=='Completed'),nightsTotal=active.reduce((s,r)=>s+stayNights(r),0),gross=active.reduce((s,r)=>s+r.gross,0);$('#performanceGrid').innerHTML=[['Forward occupancy','61%','Next 60 days'],['ADR',money(gross/nightsTotal),'All future stays'],['Average stay',`${(nightsTotal/active.length).toFixed(1)} nights`,'Mock bookings'],['Average booking value',money(gross/active.length),'Gross'],['Outstanding balances',money(active.reduce((s,r)=>s+r.balance,0)),'2–3 bookings need action'],['Direct share','31%','Opportunity to grow']].map(x=>`<article class="owner-card performance-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');$('#comparisonTable').innerHTML=[['Occupancy','55%','63%','+8 pts'],['ADR','MXN 4,050','MXN 4,258','+5.1%'],['Revenue','MXN 47,400','MXN 54,000','+13.9%'],['Direct share','24%','58%','+34 pts']].map((r,i)=>`<div class="comparison-row ${i===0?'header':''}"><span>${r[0]}</span><span>${r[1]}</span><span>${r[2]}</span><strong>${r[3]}</strong></div>`).join('')}
function renderAll(){const d=new Date(2026,7,25);$('#todayLabel').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'short',day:'numeric'}).format(d);renderOverview();renderCalendar();renderReservations();renderIntake();renderGuests();renderOperations();renderFinancials();renderPerformance()}
$('#quickAdd')?.addEventListener('click',()=>showToast('Demo: a new reservation form would open here.'));renderAll();